# Generated by Django 3.2.8 on 2021-10-11 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Editora',
            new_name='Montadora',
        ),
    ]
