# Generated by Django 3.2.7 on 2021-10-12 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_motorista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorista',
            name='CNH',
        ),
        migrations.AddField(
            model_name='motorista',
            name='cnh',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=255)),
                ('chassi', models.CharField(max_length=17)),
                ('preco', models.FloatField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='core.categoria')),
                ('montadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='core.montadora')),
            ],
        ),
    ]
