# Generated by Django 3.2.7 on 2021-10-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_montadora_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
