# Generated by Django 3.2.7 on 2021-10-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_veiculo_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
