# Generated by Django 3.2.7 on 2021-10-12 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_veiculo_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='Motorista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='core.motorista'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
