# Generated by Django 3.2.7 on 2021-10-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211012_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='Motorista',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='motorista',
            field=models.ManyToManyField(related_name='veiculos', to='core.Motorista'),
        ),
    ]
