# Generated by Django 3.2.7 on 2021-10-12 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211012_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='motorista',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='Motorista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='core.motorista'),
            preserve_default=False,
        ),
    ]
