# Generated by Django 3.2.7 on 2021-10-12 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211012_1923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Veiculo',
        ),
    ]
