# Generated by Django 3.2.7 on 2021-10-12 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_veiculo_motorista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Saída da Portaria'), (2, 'A caminho'), (3, 'Entregue na portaria'), (4, 'Viagem de retorno Iniciada'), (5, 'Se encontra na cede')], default=5)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acompanhamento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
