# Generated by Django 3.2.7 on 2021-10-12 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_acompanhamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acompanhamento',
            name='usuario',
        ),
        migrations.AddField(
            model_name='acompanhamento',
            name='veiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='acompanhamento', to='core.veiculo'),
            preserve_default=False,
        ),
    ]
