# Generated by Django 3.2.7 on 2021-10-12 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20211012_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('acompanhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.acompanhamento')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.veiculo')),
            ],
        ),
    ]
