# Generated by Django 3.2.8 on 2021-11-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20211111_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acompanhamento',
            name='motorista',
        ),
        migrations.AddField(
            model_name='itensentrega',
            name='item',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
