# Generated by Django 3.2.8 on 2021-11-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20211112_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itensentrega',
            name='item',
        ),
        migrations.AddField(
            model_name='acompanhamento',
            name='item',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
