# Generated by Django 3.2.8 on 2021-11-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20211112_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itensentrega',
            name='item',
        ),
        migrations.AddField(
            model_name='acompanhamento',
            name='item',
            field=models.CharField(default='item', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acompanhamento',
            name='quantidade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
