# Generated by Django 3.2.8 on 2021-11-13 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20211112_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acompanhamento',
            name='item',
        ),
        migrations.RemoveField(
            model_name='acompanhamento',
            name='quantidade',
        ),
    ]
