# Generated by Django 3.2.8 on 2021-11-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20211112_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanhamento',
            name='item',
            field=models.CharField(default='Item Qualquer', max_length=255),
            preserve_default=False,
        ),
    ]
