# Generated by Django 3.2.8 on 2021-11-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_acompanhamento_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanhamento',
            name='quantidade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
